### ISSUE TITLE
Export table to excel - no file for download - questions

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/data-export#1]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I've created this ticket since the data export documentation for excel is poor (or maybe I missed it).
The initial table export function
![image](https://user-images.githubusercontent.com/16973022/61706492-e4da2000-ad50-11e9-80c0-98c041a0a625.png)
returned some error related to email configuration
`
Expected response code 250 but got code "550", with message "550 5.7.1 <hello@example.com>... Access denied"
` 
(or initially the smtp server was not set/reachable)
After the configuration there is no error anymore, but...

First of, why is the mail configuration needed? is exportExcel made to send files over email, instead of giving them for download?
Second, where can i configure how export should behave and avoid emailing.

### Expected behavior
Download exported excel file in the browser.

### Actual behavior
Nothing visible happens but the excel file can be found in Files.

**Comment by aocneanu** [comment]
>I've created this ticket since the data export documentation for excel is poor

Thank you for your kind words :) .. even if this issue does not belong here (wrong repo)

Anyway, I'm sure that you can't wait to help by improving the docs and thanks in advance for that.

The excel export is designed to handle tens of millions of rows, with tens of columns. This can result in exports that easily go above 500MB and can take up to a few hours. Wouldn't you want a mail notification to know when the export is done?

From the same reason the file will never be sent by email, just a notification with a temporary download link.

Once the export is done you can download it from the files menu, as many times as you need.

Can't wait for the docs contribution ;)

**Comment by robbykrlos** [comment]
Hey, I'm not here to write kind words nor to troll. I do appreciate your sarcastic funny comment;). But there is no need for it. Just let me know what can I do to help. I'm new in this world and I'm learning on the way...

1. Could you help me find the correct repo?
2. Where (in the docs) can I contribute by documenting the excel export? 
If I search by "Excel":
![image](https://user-images.githubusercontent.com/16973022/61715040-e6adde80-ad64-11e9-8b43-6c20c58e43f0.png)
If I search by "Export"
![image](https://user-images.githubusercontent.com/16973022/61715085-fd543580-ad64-11e9-983c-715e12ef083c.png)

3. I need to know first how things are working in order to be able to document something.
4. I still think there is room for one small feature which can give the small apps the possibility to download the file as soon as it's ready

Look at the bright side... from all of our "conflicts", tickets, maybe contradictions there is more to win for everybody... at least I hope...

**Comment by aocneanu** [comment]
0. Great.

1. laravel-enso/tables is the correct repo.

2. `Notes on exporting` would be a good place to start

3. take your time

4.  >give the small apps the possibility to download the file as soon as it's ready

Enso provides this in its current state, with the mention that you, as user, don't have to stay put on the exporting page until is done. Once the export is ready you receive both push/toastr and email notifications.

From the notifications panel you can click the associated message and it will navigate you to the Files menu
or
From the email you get a direct download link with a 24 hours valability
or
You can manually go to the Files menu and download

We found the above enough but if you want to improve it we're always open to contributions.

**Comment by robbykrlos** [comment]
Fair enough.

Thank you!
