### ISSUE TITLE
Excel export: Class 'Faker\Factory' not found in production environment

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/data-export#10]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

If I try to export any table in production environment I get the following error:
`Class 'Faker\Factory' not found`
Seems like the Faker Package is used in production but only installed in dev?

![image](https://user-images.githubusercontent.com/7204559/103458706-0774b480-4d0b-11eb-9b8b-32420a28f96a.png)

Via stacktrace I found out that you use faker here - I think that's the problem?

```
class DataExportFactory extends Factory
{
    protected $model = DataExport::class;

    public function definition()
    {
        return [
            'name' => $this->faker->name(),
            'entries' => 0,
            'total' => 0,
            'status' => Statuses::Waiting,
        ];
    }
}

```
### Steps to Reproduce

1. Remove vendor dir
2. Run `composer install --prefer-dist --no-dev`
3. Try to export a table

### Expected behavior

Successful export

### Actual behavior

Error `EClass 'Faker\Factory' not found`

**Comment by raftx24** [comment]
@mauthi , thanks for reporting, yes you are right.  
fzaninotto/faker should not be in dev right now!
