### ISSUE TITLE
Description in CHANGELOG <> Code

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/data-export#11]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

In the change log of 4.5.0 you have the following part:
https://github.com/laravel-enso/enso/blob/master/CHANGELOG.md#if-generating-exports-using-the-data-export-package

The file itself looks unchanged since June 2020:
https://github.com/laravel-enso/data-export/blob/master/src/Contracts/ExportsExcel.php

Does this have any reason?

**Comment by vmcvlad** [comment]
Hi @mauthi! There is indeed an issue with the changelog which will be resolved. The [ExportsExcel](https://github.com/laravel-enso/excel/blob/master/src/Contracts/ExportsExcel.php)  contract which was actually updated and which has received support for multiple sheets is the one from the [excel package](https://github.com/laravel-enso/excel). In the future, we'll be looking into making them cross-compatible.

Meanwhile, the static `excel(...)` method on the `DataExport` model which simplifies attaching `DataExport` models to exported files has been updated to be able to handle both types of exporter instances ([Excel\ExcelExport](https://github.com/laravel-enso/excel/blob/master/src/Services/ExcelExport.php),  [DataExport\ExcelExport](https://github.com/laravel-enso/data-export/blob/master/src/Services/ExcelExport.php)) so you can use whichever suits your needs

Thank you for reporting this!

**Comment by mauthi** [comment]
Thx for the description. Works like expexted.
